---
title: ''
banner: '![Alt Text](/assets/media/image-name.jpg)'
published: true
---
safe: true
permalink: pretty
#baseurl: /
markdown: kramdown

kramdown: 
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  auto_ids: true

# Website title
title: "Corinna Jentzsch"

# Default meta description and keywords
description: "Corinna Jentzsch's website"
keywords: 
  - "political science"
  - "African politics"
  - "Mozambique"
  - "civil war"
  - "militias"
  - "contemporary political theory"

navigation:
- text: Book
  url: /violent-resistance/
- text: Research
  url: /research/
- text: Publications
  url: /publications/
- text: Teaching
  url: /teaching/
- text: CV
  url: /cv/

# Files to exclude from build
exclude: ["README.md"]

prose:
  siteurl: "http://www.corinnajentzsch.com"
  media: "assets/media"
  metadata:
    "":
      - name: "layout"
        field:
          element: "select"
          label: "Select Layout"
          placeholder: "Choose Layout"
          options:
          - name: "No Sidebar"
            value: "default"
          - name: "With Sidebar"
            value: "sidebar"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "banner"
        field:
          element: "text"
          label: "Banner Image (Use Markdown)"
          value: "![Alt Text](/assets/media/image-name.jpg)"
    _includes: []
  ignore:
    - /humans.txt
    - /robots.txt
    - /README.md
    - /CNAME
    - /404.html
    - /.gitignore
